AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploys two EC2 instances with public IPs and SSH-only security group rules.'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC ID where the security group will be created.'

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: 'The public Subnet ID where the EC2 instances will be launched. Ensure this subnet is associated with a route to an Internet Gateway.'

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'The name of the EC2 Key Pair to associate with the instances for SSH access.'

  InstanceType:
    Type: String
    Default: t3.micro
    Description: 'The EC2 instance type.'

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64'
    Description: 'The SSM parameter path to fetch the latest Amazon Linux 2023 AMI ID.'

Resources:
  # =========================================================================
  # Security Group (Inbound TCP/22 Only)
  # =========================================================================
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Permit inbound SSH traffic only'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: yor_name
          Value: InstanceSecurityGroup
        - Key: git_repo
          Value: gocortexbrokenbank-c2c
        - Key: git_org
          Value: fl-nch
        - Key: git_modifiers
          Value: 156729790+fl-nch
        - Key: git_last_modified_by
          Value: 156729790+fl-nch@users.noreply.github.com
        - Key: git_last_modified_at
          Value: "2026-06-17 02:17:28"
        - Key: git_file
          Value: aws/sflab-aws-jun26-ec2runtimetesting.yaml
        - Key: yor_trace
          Value: dcd5ee9d-086a-4949-aab7-de61108bd35a
        - Key: git_commit
          Value: 307c4cea96825fbc28ea736c256f7a75ad3ca298

  # =========================================================================
  # EC2 Instances
  # =========================================================================
  XdrAgentInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: runtimetest-xdragent
        - Key: git_org
          Value: fl-nch
        - Key: git_last_modified_by
          Value: 156729790+fl-nch@users.noreply.github.com
        - Key: git_file
          Value: aws/sflab-aws-jun26-ec2runtimetesting.yaml
        - Key: git_commit
          Value: 307c4cea96825fbc28ea736c256f7a75ad3ca298
        - Key: yor_trace
          Value: 248e4da5-e212-476c-83f3-3a466b025cee
        - Key: yor_name
          Value: XdrAgentInstance
        - Key: git_repo
          Value: gocortexbrokenbank-c2c
        - Key: git_modifiers
          Value: 156729790+fl-nch
        - Key: git_last_modified_at
          Value: "2026-06-17 02:17:28"
  AgentlessInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      KeyName: !Ref KeyPairName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          SubnetId: !Ref SubnetId
          GroupSet:
            - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: runtimetest-agentless
        - Key: git_last_modified_at
          Value: "2026-06-17 02:17:28"
        - Key: git_file
          Value: aws/sflab-aws-jun26-ec2runtimetesting.yaml
        - Key: git_commit
          Value: 307c4cea96825fbc28ea736c256f7a75ad3ca298
        - Key: yor_trace
          Value: 5d38747b-392f-4ef3-95fe-05a64facba32
        - Key: yor_name
          Value: AgentlessInstance
        - Key: git_org
          Value: fl-nch
        - Key: git_last_modified_by
          Value: 156729790+fl-nch@users.noreply.github.com
        - Key: git_repo
          Value: gocortexbrokenbank-c2c
        - Key: git_modifiers
          Value: 156729790+fl-nch

Outputs:
  XdrAgentPublicIp:
    Description: 'Public IP of the runtimetest-xdragent instance'
    Value: !GetAtt XdrAgentInstance.PublicIp

  AgentlessPublicIp:
    Description: 'Public IP of the runtimetest-agentless instance'
    Value: !GetAtt AgentlessInstance.PublicIp